# Generated by Django 6.1.1 on 2026-09-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del chatbot.', max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción del chatbot.', verbose_name='descripción')),
                ('modelo', models.CharField(choices=[('openai/gpt-4o-mini', 'GPT-4o Mini'), ('openai/gpt-4o', 'GPT-4o'), ('openai/gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('anthropic/claude-3-5-sonnet', 'Claude 3.5 Sonnet'), ('anthropic/claude-3-haiku', 'Claude 3 Haiku'), ('meta-llama/llama-3.1-8b-instruct', 'Llama 3.1 8B'), ('meta-llama/llama-3.1-70b-instruct', 'Llama 3.1 70B'), ('google/gemini-2.0-flash-001', 'Gemini 2.0 Flash'), ('google/gemini-pro', 'Gemini Pro'), ('mistralai/mixtral-8x7b-instruct', 'Mixtral 8x7B'), ('deepseek/deepseek-chat', 'DeepSeek Chat'), ('qwen/qwen-2-72b-instruct', 'Qwen 2 72B'), ('cohere/command-r-plus', 'Command R+'), ('perplexity/sonar-small-online', 'Sonar Small Online')], default='openai/gpt-4o-mini', help_text='Modelo LLM a utilizar.', max_length=100, verbose_name='modelo')),
                ('slug', models.SlugField(blank=True, help_text='URL amigable generada automáticamente.', unique=True, verbose_name='slug')),
                ('instructions', models.TextField(blank=True, default='', help_text='Instrucciones personalizadas para el chatbot.', verbose_name='instrucciones')),
                ('is_public', models.BooleanField(default=False, help_text='Si es público, cualquiera puede chatear.', verbose_name='es público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'chatbot',
                'verbose_name_plural': 'chatbots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Contenido del mensaje.', verbose_name='contenido')),
                ('is_user', models.BooleanField(default=True, help_text='True si es mensaje del usuario, False si es del asistente.', verbose_name='es usuario')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='marca de tiempo')),
            ],
            options={
                'verbose_name': 'mensaje de chat',
                'verbose_name_plural': 'mensajes de chat',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'sesión de chat',
                'verbose_name_plural': 'sesiones de chat',
                'ordering': ['-updated_at'],
            },
        ),
    ]
