# Generated by Django 6.1.1 on 2026-09-20 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots_creados', to=settings.AUTH_USER_MODEL, verbose_name='creador'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='chatbots_compartidos', to=settings.AUTH_USER_MODEL, verbose_name='compartido con'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='chatbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chatbots.chatbot', verbose_name='chatbot'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbots.chatsession', verbose_name='sesión'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['slug'], name='chatbots_ch_slug_3180f9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['creador'], name='chatbots_ch_creador_94651d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['is_public'], name='chatbots_ch_is_publ_69f984_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['created_at'], name='chatbots_ch_created_cbf1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['chatbot', 'user'], name='chatbots_ch_chatbot_d50683_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(fields=('chatbot', 'user'), name='unique_active_session'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='chatbots_ch_session_d7ead3_idx'),
        ),
    ]
