# Generated by Django 6.1.1 on 2026-09-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='acciones',
            field=models.TextField(blank=True, default='', help_text='Acciones que el chatbot puede realizar (ej: enviar emails, crear tareas).', verbose_name='acciones'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='documentacion',
            field=models.TextField(blank=True, default='', help_text='Documentación de referencia que el chatbot usa para responder.', verbose_name='documentación'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='funciones',
            field=models.TextField(blank=True, default='', help_text='Capacidades específicas del chatbot (ej: "buscar información", "generar código").', verbose_name='funciones'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='icon',
            field=models.CharField(default='🤖', help_text='Emoji representativo del chatbot.', max_length=10, verbose_name='icono'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='soul',
            field=models.TextField(blank=True, default='', help_text='La personalidad y esencia del chatbot. ¿Quién es? ¿Cómo se comporta?', verbose_name='alma'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Instrucciones técnicas: cómo formatear respuestas, límites, reglas.', verbose_name='instrucciones'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='modelo',
            field=models.CharField(choices=[('meta-llama/llama-3.1-8b-instruct', 'Llama 3.1 8B'), ('meta-llama/llama-3.2-3b-instruct', 'Llama 3.2 3B'), ('google/gemma-2-9b-it', 'Gemma 2 9B'), ('google/gemma-2-2b-it', 'Gemma 2 2B'), ('mistralai/mistral-7b-instruct', 'Mistral 7B'), ('qwen/qwen-2-7b-instruct', 'Qwen 2 7B'), ('deepseek/deepseek-chat', 'DeepSeek Chat'), ('openai/gpt-4o-mini', 'GPT-4o Mini'), ('openai/gpt-4o', 'GPT-4o'), ('anthropic/claude-3-5-sonnet', 'Claude 3.5 Sonnet'), ('anthropic/claude-3-haiku', 'Claude 3 Haiku'), ('google/gemini-2.0-flash-001', 'Gemini 2.0 Flash'), ('google/gemini-pro', 'Gemini Pro'), ('meta-llama/llama-3.1-70b-instruct', 'Llama 3.1 70B'), ('mistralai/mixtral-8x7b-instruct', 'Mixtral 8x7B'), ('qwen/qwen-2-72b-instruct', 'Qwen 2 72B'), ('cohere/command-r-plus', 'Command R+')], default='openai/gpt-4o-mini', help_text='Modelo LLM a utilizar.', max_length=100, verbose_name='modelo'),
        ),
    ]
