# Generated by Django 6.1.1 on 2026-09-20 21:02

import apps.chatbots.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0007_chatbot_documentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='documentacion',
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='icon',
            field=models.ImageField(blank=True, default='', help_text='Imagen representativa del chatbot (subida por el usuario).', null=True, upload_to='chat_icons/', validators=[apps.chatbots.models.validate_file_size], verbose_name='icono'),
        ),
        migrations.AlterField(
            model_name='chatbotdocument',
            name='file',
            field=models.FileField(help_text='Archivo de documentación (pdf, json, docx, doc, txt, works, rtf, etc.).', upload_to='chat_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'json', 'txt', 'docx', 'rtf', 'doc']), apps.chatbots.models.validate_file_size], verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='chatbotdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalchatbot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
