# Generated by Django 6.1.1 on 2026-09-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0011_remove_acciones_add_templates'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatsession',
            name='unique_active_session',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='is_public_via_url',
            field=models.BooleanField(default=False, help_text='Si es visible vía URL, el chatbot es accesible mediante su slugaunque no sea público general. Las conversaciones siguen estando aisladas por usuario.', verbose_name='visible vía URL'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Si es público, cualquiera puede chatear y aparecer en directorios.', verbose_name='es público'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='modelo',
            field=models.CharField(choices=[('meta-llama/llama-3.1-8b-instruct', 'Llama 3.1 8B'), ('meta-llama/llama-3.2-3b-instruct', 'Llama 3.2 3B'), ('google/gemma-2-9b-it', 'Gemma 2 9B'), ('google/gemma-2-2b-it', 'Gemma 2 2B'), ('mistralai/mistral-7b-instruct', 'Mistral 7B'), ('qwen/qwen-2-7b-instruct', 'Qwen 2 7B'), ('deepseek/deepseek-chat', 'DeepSeek Chat')], default='meta-llama/llama-3.1-8b-instruct', help_text='Modelo LLM a utilizar.', max_length=100, verbose_name='modelo'),
        ),
    ]
