# Generated by Django 6.1.1 on 2026-09-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0012_remove_chatsession_unique_active_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='funciones',
        ),
        migrations.RemoveField(
            model_name='chatbottemplate',
            name='funciones',
        ),
    ]
