# Generated by Django 6.1.1 on 2026-09-22 02:39

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.core.validators.validate_file_size], verbose_name='avatar'),
        ),
    ]
